=== marianieva/AE-2.XML-DTD-y-XSD/XSD_Biblioteca_Mikel.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="libros">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="libro" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="titulo" type="xs:string"/>
                                    <xs:element name="capitulos">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="capitulo_01" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name ="titulo"/>
                                                            <xs:element name ="contenido"/>
                                                        </xs:sequence>
                                                        <xs:attribute name="numero_paginas">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:integer">
                                                                    <xs:minInclusive value="0"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="capitulo_02" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name ="titulo"/>
                                                            <xs:element name ="contenido"/>
                                                        </xs:sequence>
                                                        <xs:attribute name="numero_paginas">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:integer">
                                                                    <xs:minInclusive value="0"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="capitulo_03" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name ="titulo"/>
                                                            <xs:element name ="contenido"/>
                                                        </xs:sequence>
                                                        <xs:attribute name="numero_paginas">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:integer">
                                                                    <xs:minInclusive value="0"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="indice"/>
                                    <xs:element name="sinopsis"/>
                                </xs:sequence>
                                <xs:attribute name="id" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                        <xs:pattern value="L[0-9]{4}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="tipo_clase">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="Novela"/>
                                            <xs:enumeration value="Infantil"/>
                                            <xs:enumeration value="DidÃ¡ctico"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="numero_paginas">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="0"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
                </xs:element>


                <xs:element name="revistas">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="revista" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="titulo"/>
                                    <xs:element name="numero_revista"/>
                                    <xs:element name="indice"/>
                                    <xs:element name="seccion_01">
                                        <xs:complexType>
                                            <xs:sequence>
                                             <xs:element name="nombre"/>
                                             <xs:element name="contenido"/>
                                            </xs:sequence>
                                            <xs:attribute name="numero_paginas">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:integer">
                                                        <xs:minInclusive value="0"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:complexType>
                                    </xs:element>
                                     <xs:element name="seccion_02">
                                        <xs:complexType>
                                            <xs:sequence>
                                             <xs:element name="nombre"/>
                                             <xs:element name="contenido"/>
                                            </xs:sequence>
                                            <xs:attribute name="numero_paginas">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:integer">
                                                        <xs:minInclusive value="0"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:complexType>
                                    </xs:element>
                                     <xs:element name="seccion_03">
                                        <xs:complexType>
                                            <xs:sequence>
                                             <xs:element name="nombre"/>
                                             <xs:element name="contenido"/>
                                            </xs:sequence>
                                            <xs:attribute name="numero_paginas">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:integer">
                                                        <xs:minInclusive value="0"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="id" use="required">
                                <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                        <xs:pattern value="R[0-9]{4}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="tipo_clase">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="InformÃ¡tica"/>
                                            <xs:enumeration value="Corazon"/>
                                            <xs:enumeration value="Coches"/>
                                            <xs:enumeration value="InvestigaciÃ³n"/>
                                            <xs:enumeration value="Otros"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="numero_paginas">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="0"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
                </xs:element>


                <xs:element name="periodicos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="periodico" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="seccion " maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="articulo_01">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="titulo"/>
                                                            <xs:element name="contenido"/>
                                                        </xs:sequence>
                                                        <xs:attribute name="autor">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="articulo_02">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="titulo"/>
                                                            <xs:element name="contenido"/>
                                                        </xs:sequence>
                                                        <xs:attribute name="autor">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="articulo_03">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="titulo"/>
                                                            <xs:element name="contenido"/>
                                                        </xs:sequence>
                                                        <xs:attribute name="autor">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                            <xs:attribute name="tipo_seccion">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="Economica"/>
                                                        <xs:enumeration value="Opinion"/>
                                                        <xs:enumeration value="Deportes"/>
                                                        <xs:enumeration value="Nacional"/>
                                                        <xs:enumeration value="Internacional"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="indice"/>
                                    
                                </xs:sequence>
                                <xs:attribute name="id" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                        <xs:pattern value="P[0-9]{4}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="tipo_clase">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="Nacional"/>
                                            <xs:enumeration value="Internacional"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="fecha_publicacion" type="xs:date"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marianieva/AE-2.XML-DTD-y-XSD/Biblioteca_mikel_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "XSD_Biblioteca_Mikel.xsd">


    <libros>
         <libro id="L0001" tipo_clase="Novela" numero_paginas="92">
            <titulo>El coronel no tiene quien le escriba</titulo>
            <capitulos>
                <capitulo_01 numero_paginas="10">
                    <titulo>El coronel y su libreta</titulo>
                    <contenido info="https://rinconliterario256.wordpress.com/sinopsis-de-libros/"></contenido>
                </capitulo_01>
                <capitulo_02 numero_paginas="8">
                    <titulo>El coronel y la esposa</titulo>
                    <contenido info="https://rinconliterario256.wordpress.com/sinopsis-de-libros/"></contenido>
                </capitulo_02>
                <capitulo_03 numero_paginas="16">
                    <titulo>Veterano de la guerra</titulo>
                    <contenido info="https://rinconliterario256.wordpress.com/sinopsis-de-libros/"></contenido>
                </capitulo_03>
            </capitulos>
            <indice>
                    1-El coronel y su libreta
                    2-El coronel y la esposa
                    3-Veterano de la guerra
            </indice>
            <sinopsis>La historia narra tres meses de la vida del coronel y de su esposa </sinopsis>
        </libro>

        <libro id="L0002" tipo_clase="Didáctico" numero_paginas="109">
            <titulo>Lo que no se dice </titulo>
            <capitulos>
                <capitulo_01 numero_paginas="12">
                    <titulo>Hoy</titulo>
                    <contenido info="https://rinconliterario256.wordpress.com/sinopsis-de-libros/"></contenido>
                </capitulo_01>
                <capitulo_02 numero_paginas="14">
                    <titulo>Ayer</titulo>
                    <contenido info="https://rinconliterario256.wordpress.com/sinopsis-de-libros/"></contenido>
                </capitulo_02>
                <capitulo_03 numero_paginas="9">
                    <titulo>Mañana</titulo>
                    <contenido info="https://rinconliterario256.wordpress.com/sinopsis-de-libros/"></contenido>
                </capitulo_03>
            </capitulos>
            <indice>
                    1-Hoy
                    2-Ayer
                    3-Mañana
             </indice>
             <sinopsis>Dos historias de amor, una actual y otra antigua </sinopsis>
         
        </libro>

        <libro id="L0003" tipo_clase="Infantil" numero_paginas="32">
            <titulo>El pequeño mundo de los colores olvidados</titulo>
            <capitulos>
                <capitulo_01 numero_paginas="4">
                    <titulo>Gato negro</titulo>
                    <contenido info="https://rinconliterario256.wordpress.com/sinopsis-de-libros/"></contenido>
                </capitulo_01>
                <capitulo_02 numero_paginas="5">
                    <titulo>La niña azul</titulo>
                    <contenido info="https://rinconliterario256.wordpress.com/sinopsis-de-libros/"></contenido>
                </capitulo_02>
                <capitulo_03 numero_paginas="7">
                    <titulo>El niño verde</titulo>
                    <contenido info="https://rinconliterario256.wordpress.com/sinopsis-de-libros/"></contenido>
                </capitulo_03>
            </capitulos>
            <indice>
                    1-Gato negro
                    2-La niña azul
                    3-El niño verde
            
            </indice>
            <sinopsis>Los colores olvidados”,libro ilustrado lleno de magia con tres personajes carismáticos: Carmesina, Serafín y Gato Negro. ¿Nos ayudas a pintar el mundo?</sinopsis>
        </libro>

       </libros>

     <revistas>

        <revista id="R0001" tipo_clase="Coches" numero_paginas="43">
            <titulo>AutoBild</titulo>
            <numero_revista>653</numero_revista>
            <indice>
                 1-Coches actuales
                 2-20 Nuevos modelos
                 3-Neumaticos de verano 
            </indice>
            <seccion_01 numero_paginas="2">
                <nombre>Coches actuales</nombre>
                <contenido info="https://www.kioskoymas.com/Publicacion/portada/autobild/2005"></contenido>
            </seccion_01>
            <seccion_02 numero_paginas="3">
                <nombre>20 Nuevos modelos</nombre>
                <contenido info="https://www.kioskoymas.com/Publicacion/portada/autobild/2005"></contenido>
            </seccion_02>
            <seccion_03 numero_paginas="5">
                <nombre>Neumaticos de verano</nombre>
                <contenido info="https://www.kioskoymas.com/Publicacion/portada/autobild/2005"></contenido>
            </seccion_03>
        </revista>

        <revista id="R0002" tipo_clase="Investigación" numero_paginas="90">
            <titulo>Muy interesante</titulo>
            <numero_revista>504</numero_revista>
            <indice>
                1-Cueva del arco
                2-Ecosistema
                3-Inteligencia artificial
            </indice>
            <seccion_01 numero_paginas="10">
                <nombre>Cueva del arco</nombre>
                <contenido info= "https://lectura.kioskoymas.com/muy-interesante/20230421"></contenido>
            </seccion_01>
            <seccion_02 numero_paginas="14">
                <nombre>Ecosistema</nombre>
                <contenido info="https://lectura.kioskoymas.com/muy-interesante/20230421"></contenido>
            </seccion_02>
             <seccion_03 numero_paginas="21">
                <nombre>Inteligencia artificial</nombre>
                <contenido info="https://lectura.kioskoymas.com/muy-interesante/20230421"></contenido>
            </seccion_03>
        </revista>

        <revista id="R0003" tipo_clase="Informática" numero_paginas="75">
            <titulo>Computer hoy </titulo>
            <numero_revista>642</numero_revista>
            <indice>
                1-La biblia de los cables
                2-Mantenimiento pc
                3-Control parental
            </indice>
            <seccion_01 numero_paginas="3">
                <nombre>La biblia de los cables</nombre>
                <contenido info="https://lectura.kioskoymas.com/computer-hoy/20230512"></contenido>
            </seccion_01>
            <seccion_02 numero_paginas="25">
                <nombre>Mantenimiento pc</nombre>
                <contenido info="https://lectura.kioskoymas.com/computer-hoy/20230512"></contenido>
            </seccion_02>
            <seccion_03 numero_paginas="25">
                <nombre>Control parental</nombre>
                <contenido info="https://lectura.kioskoymas.com/computer-hoy/20230512"></contenido>
            </seccion_03>
        </revista>

    </revistas>

    <periodicos>

        <periodico id="P0001" tipo_clase="Nacional" fecha_publicacion= "2023-04-14">

            <seccion tipo_seccion="Economica">
                <articulo_01 autor="Guillermo Maestre">
                    <titulo>Nuevo precio del tabaco</titulo>
                    <contenido info="https://www.heraldo.es/noticias/economia/2023/05/14/boe-publica-nuevo-precio-tabaco-marcas-cigarros-1651562.html"></contenido>
                </articulo_01>
                <articulo_02 autor="Pixabay">
                    <titulo>El precio de la luz</titulo>
                    <contenido info="https://www.heraldo.es/noticias/economia/2023/05/14/precio-luz-hoy-domingo-horas-gratis-baratas-1651554.html"></contenido>
                </articulo_02>
                <articulo_03 autor="Guillermo Mestre">
                    <titulo>La contruccion </titulo>
                    <contenido info="https://www.heraldo.es/noticias/economia/2023/05/14/construccion-zaragoza-cambio-normativa-adelantar-jornada-calor-verano-1651512.html"></contenido>
                </articulo_03>

            </seccion>
            <seccion tipo_seccion="Opinion">
                <articulo_01 autor="Pexels">
                    <titulo>Estrategia contra la sequia</titulo>
                    <contenido info="https://www.heraldo.es/noticias/opinion/2023/05/14/estrategias-contra-la-sequia-editorial-1651321.html"></contenido>
                </articulo_01>
                <articulo_02 autor="Santiago Mendive">
                    <titulo>Secuestradores, asesinos y legisladores</titulo>
                    <contenido info="https://www.heraldo.es/noticias/opinion/2023/05/14/secuestradores-asesinos-legisladores-1651419.html"></contenido>
                </articulo_02>
                <articulo_03 autor="Jose Javier Rueda">
                    <titulo>Lunas para todos</titulo>
                    <contenido info="https://www.heraldo.es/noticias/opinion/2023/05/14/lunas-para-todos-jose-javier-rueda-1651300.html"></contenido>
                </articulo_03>
            </seccion>

            <seccion tipo_seccion="Nacional">
                <articulo_01 autor="José M. Camarero">
                    <titulo>Los embalses</titulo>
                    <contenido info="https://www.heraldo.es/noticias/nacional/2023/05/14/los-embalses-hacen-equilibrios-para-generar-luz-en-plena-epoca-de-sequia-1651502.html"></contenido>
                </articulo_01>
                <articulo_02 autor="Paula Boira">
                    <titulo>Violencia Obstétrica</titulo>
                    <contenido info="https://www.heraldo.es/noticias/nacional/2023/05/13/violencia-obstetrica-limites-mujer-decidir-parto-1651458.html"></contenido>
                </articulo_02>
                <articulo_03 autor="José Antonio Guerrero">
                    <titulo>La alcaldesa mas veterana del mundo</titulo>
                    <contenido info="https://www.heraldo.es/noticias/nacional/2023/05/13/charito-alcaldable-mas-veterana-mundo-elecciones-espana-1651290.html"></contenido>
                </articulo_03>
